import type { Metadata } from "next";
import "./bulma.scss";

export const metadata: Metadata = {
    title: "InScrompT | Building products for humans",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
