name: Deploy Inscrompt landing page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FIDDLE_IP }}
          username: inscrompt
          key: ${{ secrets.SSH_INSCROMPT_PRIVATE }}
          script: |
            export PATH=$HOME/.nvm/versions/node/v22.6.0/bin:$PATH
            cd ~/htdocs/inscrompt.com && git pull && pnpm build && pm2 restart inscrompt
