name: Deploy Inscrompt landing page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_INSCROMPT_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FIDDLE_IP }}
          username: inscrompt
          key: ${{ secrets.SSH_INSCROMPT_PRIVATE }}
          passphrase: ${{ secrets.SSH_INSCROMPT_PASSPHRASE }}
          script: |
            cd ~/htdocs/inscrompt.com && git pull && pnpm install && pnpm build
